// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apiv1alpha1 "sigs.k8s.io/agent-sandbox/api/v1alpha1"
)

// LifecycleApplyConfiguration represents a declarative configuration of the Lifecycle type for use
// with apply.
//
// Lifecycle defines the lifecycle management for the Sandbox.
type LifecycleApplyConfiguration struct {
	// shutdownTime is the absolute time when the sandbox expires.
	ShutdownTime *v1.Time `json:"shutdownTime,omitempty"`
	// shutdownPolicy determines if the Sandbox resource itself should be deleted when it expires.
	// Underlying resources(Pods, Services) are always deleted on expiry.
	ShutdownPolicy *apiv1alpha1.ShutdownPolicy `json:"shutdownPolicy,omitempty"`
}

// LifecycleApplyConfiguration constructs a declarative configuration of the Lifecycle type for use with
// apply.
func Lifecycle() *LifecycleApplyConfiguration {
	return &LifecycleApplyConfiguration{}
}

// WithShutdownTime sets the ShutdownTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShutdownTime field is set to the value of the last call.
func (b *LifecycleApplyConfiguration) WithShutdownTime(value v1.Time) *LifecycleApplyConfiguration {
	b.ShutdownTime = &value
	return b
}

// WithShutdownPolicy sets the ShutdownPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShutdownPolicy field is set to the value of the last call.
func (b *LifecycleApplyConfiguration) WithShutdownPolicy(value apiv1alpha1.ShutdownPolicy) *LifecycleApplyConfiguration {
	b.ShutdownPolicy = &value
	return b
}
