// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// PodTemplateApplyConfiguration represents a declarative configuration of the PodTemplate type for use
// with apply.
type PodTemplateApplyConfiguration struct {
	// spec is the Pod's spec
	Spec *v1.PodSpec `json:"spec,omitempty"`
	// metadata is the Pod's metadata. Only labels and annotations are used.
	ObjectMeta *PodMetadataApplyConfiguration `json:"metadata,omitempty"`
}

// PodTemplateApplyConfiguration constructs a declarative configuration of the PodTemplate type for use with
// apply.
func PodTemplate() *PodTemplateApplyConfiguration {
	return &PodTemplateApplyConfiguration{}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *PodTemplateApplyConfiguration) WithSpec(value v1.PodSpec) *PodTemplateApplyConfiguration {
	b.Spec = &value
	return b
}

// WithObjectMeta sets the ObjectMeta field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObjectMeta field is set to the value of the last call.
func (b *PodTemplateApplyConfiguration) WithObjectMeta(value *PodMetadataApplyConfiguration) *PodTemplateApplyConfiguration {
	b.ObjectMeta = value
	return b
}
