// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apiv1alpha1 "sigs.k8s.io/agent-sandbox/api/v1alpha1"
)

// SandboxSpecApplyConfiguration represents a declarative configuration of the SandboxSpec type for use
// with apply.
//
// SandboxSpec defines the desired state of Sandbox.
type SandboxSpecApplyConfiguration struct {
	// podTemplate describes the pod spec that will be used to create an agent sandbox.
	PodTemplate *PodTemplateApplyConfiguration `json:"podTemplate,omitempty"`
	// volumeClaimTemplates is a list of claims that the sandbox pod is allowed to reference.
	// Every claim in this list must have at least one matching access mode with a provisioner volume.
	VolumeClaimTemplates []PersistentVolumeClaimTemplateApplyConfiguration `json:"volumeClaimTemplates,omitempty"`
	// Lifecycle defines when and how the sandbox should be shut down.
	LifecycleApplyConfiguration `json:",inline"`
	// replicas is the number of desired replicas.
	// The only allowed values are 0 and 1.
	// Defaults to 1.
	Replicas *int32 `json:"replicas,omitempty"`
	// service controls whether the controller should automatically create a
	// headless Service for this Sandbox.
	// When unset, the controller preserves existing Services for backward
	// compatibility but does not create new ones. Set to true to enable or false
	// to explicitly disable and remove the Service.
	Service *bool `json:"service,omitempty"`
}

// SandboxSpecApplyConfiguration constructs a declarative configuration of the SandboxSpec type for use with
// apply.
func SandboxSpec() *SandboxSpecApplyConfiguration {
	return &SandboxSpecApplyConfiguration{}
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *SandboxSpecApplyConfiguration) WithPodTemplate(value *PodTemplateApplyConfiguration) *SandboxSpecApplyConfiguration {
	b.PodTemplate = value
	return b
}

// WithVolumeClaimTemplates adds the given value to the VolumeClaimTemplates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeClaimTemplates field.
func (b *SandboxSpecApplyConfiguration) WithVolumeClaimTemplates(values ...*PersistentVolumeClaimTemplateApplyConfiguration) *SandboxSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumeClaimTemplates")
		}
		b.VolumeClaimTemplates = append(b.VolumeClaimTemplates, *values[i])
	}
	return b
}

// WithShutdownTime sets the ShutdownTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShutdownTime field is set to the value of the last call.
func (b *SandboxSpecApplyConfiguration) WithShutdownTime(value v1.Time) *SandboxSpecApplyConfiguration {
	b.LifecycleApplyConfiguration.ShutdownTime = &value
	return b
}

// WithShutdownPolicy sets the ShutdownPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShutdownPolicy field is set to the value of the last call.
func (b *SandboxSpecApplyConfiguration) WithShutdownPolicy(value apiv1alpha1.ShutdownPolicy) *SandboxSpecApplyConfiguration {
	b.LifecycleApplyConfiguration.ShutdownPolicy = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *SandboxSpecApplyConfiguration) WithReplicas(value int32) *SandboxSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *SandboxSpecApplyConfiguration) WithService(value bool) *SandboxSpecApplyConfiguration {
	b.Service = &value
	return b
}
