// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "sigs.k8s.io/agent-sandbox/api/v1alpha1"
	extensionsapiv1alpha1 "sigs.k8s.io/agent-sandbox/extensions/api/v1alpha1"
)

// SandboxTemplateSpecApplyConfiguration represents a declarative configuration of the SandboxTemplateSpec type for use
// with apply.
//
// SandboxTemplateSpec defines the desired state of Sandbox.
type SandboxTemplateSpecApplyConfiguration struct {
	// podTemplate defines the object template that describes the pod spec that will be used to create
	// an agent sandbox.
	// If AutomountServiceAccountToken is not specified in the PodSpec, it defaults to false
	// to ensure a secure-by-default environment.
	PodTemplate *apiv1alpha1.PodTemplate `json:"podTemplate,omitempty"`
	// volumeClaimTemplates is a list of claims that pods created from this template
	// are allowed to reference. When a SandboxClaim or SandboxWarmPool creates a sandbox
	// from this template, PVCs will be created from these templates.
	// Every claim in this list must have at least one matching access mode with a provisioner volume.
	// NOTE: This list is atomic. Updates to this field will replace the entire list rather than merging with existing entries.
	VolumeClaimTemplates []apiv1alpha1.PersistentVolumeClaimTemplate `json:"volumeClaimTemplates,omitempty"`
	// networkPolicy defines the network policy to be applied to the sandboxes
	// created from this template. A single shared NetworkPolicy is created per Template.
	// Behavior is dictated by the NetworkPolicyManagement field:
	// - If Management is "Unmanaged": This field is completely ignored.
	// - If Management is "Managed" (default) and this field is omitted (nil): The controller
	// automatically applies a strict Secure Default policy:
	// * Ingress: Allow traffic only from the Sandbox Router.
	// * Egress: Allow Public Internet only. Blocks internal IPs (RFC1918), Metadata Server, etc.
	// - If Management is "Managed" and this field is provided: The controller applies your custom rules.
	// Update Behavior:
	// Because the NetworkPolicy is shared at the template level, any updates to these rules
	// will be applied to the single shared policy object. The underlying Kubernetes CNI will then
	// dynamically enforce the updated rules across all existing and future sandboxes
	// referencing this template.
	// NOTE: This is a restricted subset of the standard Kubernetes NetworkPolicySpec.
	// Fields like 'PodSelector' and 'PolicyTypes' are intentionally excluded because
	// they are managed by the controller to ensure strict isolation and default-deny posture.
	// WARNING: This policy enforces a strict "Default Deny" ingress posture.
	// If your Pod uses sidecars (e.g., Istio proxy, monitoring agents) that listen
	// on their own ports, the NetworkPolicy will BLOCK traffic to them by default.
	// You MUST explicitly allow traffic to these sidecar ports using 'Ingress',
	// otherwise the sidecars may fail health checks.
	NetworkPolicy *NetworkPolicySpecApplyConfiguration `json:"networkPolicy,omitempty"`
	// networkPolicyManagement defines whether the controller manages the NetworkPolicy.
	// Valid values are "Managed" (default) or "Unmanaged".
	NetworkPolicyManagement *extensionsapiv1alpha1.NetworkPolicyManagement `json:"networkPolicyManagement,omitempty"`
	// envVarsInjectionPolicy allows a SandboxClaim to inject or override environment variables defined in the template.
	// If set to Disallowed, the SandboxClaim will be rejected if it specifies any environment variables.
	EnvVarsInjectionPolicy *extensionsapiv1alpha1.EnvVarsInjectionPolicy `json:"envVarsInjectionPolicy,omitempty"`
	// service controls whether the controller should automatically create a
	// headless Service for Sandboxes created from this template.
	// When unset, the controller preserves existing Services for backward
	// compatibility but does not create new ones. Set to true to enable or false
	// to explicitly disable and remove the Service.
	Service *bool `json:"service,omitempty"`
}

// SandboxTemplateSpecApplyConfiguration constructs a declarative configuration of the SandboxTemplateSpec type for use with
// apply.
func SandboxTemplateSpec() *SandboxTemplateSpecApplyConfiguration {
	return &SandboxTemplateSpecApplyConfiguration{}
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *SandboxTemplateSpecApplyConfiguration) WithPodTemplate(value apiv1alpha1.PodTemplate) *SandboxTemplateSpecApplyConfiguration {
	b.PodTemplate = &value
	return b
}

// WithVolumeClaimTemplates adds the given value to the VolumeClaimTemplates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeClaimTemplates field.
func (b *SandboxTemplateSpecApplyConfiguration) WithVolumeClaimTemplates(values ...apiv1alpha1.PersistentVolumeClaimTemplate) *SandboxTemplateSpecApplyConfiguration {
	for i := range values {
		b.VolumeClaimTemplates = append(b.VolumeClaimTemplates, values[i])
	}
	return b
}

// WithNetworkPolicy sets the NetworkPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkPolicy field is set to the value of the last call.
func (b *SandboxTemplateSpecApplyConfiguration) WithNetworkPolicy(value *NetworkPolicySpecApplyConfiguration) *SandboxTemplateSpecApplyConfiguration {
	b.NetworkPolicy = value
	return b
}

// WithNetworkPolicyManagement sets the NetworkPolicyManagement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkPolicyManagement field is set to the value of the last call.
func (b *SandboxTemplateSpecApplyConfiguration) WithNetworkPolicyManagement(value extensionsapiv1alpha1.NetworkPolicyManagement) *SandboxTemplateSpecApplyConfiguration {
	b.NetworkPolicyManagement = &value
	return b
}

// WithEnvVarsInjectionPolicy sets the EnvVarsInjectionPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnvVarsInjectionPolicy field is set to the value of the last call.
func (b *SandboxTemplateSpecApplyConfiguration) WithEnvVarsInjectionPolicy(value extensionsapiv1alpha1.EnvVarsInjectionPolicy) *SandboxTemplateSpecApplyConfiguration {
	b.EnvVarsInjectionPolicy = &value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *SandboxTemplateSpecApplyConfiguration) WithService(value bool) *SandboxTemplateSpecApplyConfiguration {
	b.Service = &value
	return b
}
