// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SandboxWarmPoolStatusApplyConfiguration represents a declarative configuration of the SandboxWarmPoolStatus type for use
// with apply.
//
// SandboxWarmPoolStatus defines the observed state of SandboxWarmPool.
type SandboxWarmPoolStatusApplyConfiguration struct {
	// replicas is the total number of sandboxes in the pool.
	Replicas *int32 `json:"replicas,omitempty"`
	// readyReplicas is the total number of sandboxes in the pool that are in a ready state.
	ReadyReplicas *int32 `json:"readyReplicas,omitempty"`
	// selector is the label selector used to find the pods in the pool.
	Selector *string `json:"selector,omitempty"`
}

// SandboxWarmPoolStatusApplyConfiguration constructs a declarative configuration of the SandboxWarmPoolStatus type for use with
// apply.
func SandboxWarmPoolStatus() *SandboxWarmPoolStatusApplyConfiguration {
	return &SandboxWarmPoolStatusApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *SandboxWarmPoolStatusApplyConfiguration) WithReplicas(value int32) *SandboxWarmPoolStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *SandboxWarmPoolStatusApplyConfiguration) WithReadyReplicas(value int32) *SandboxWarmPoolStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *SandboxWarmPoolStatusApplyConfiguration) WithSelector(value string) *SandboxWarmPoolStatusApplyConfiguration {
	b.Selector = &value
	return b
}
