// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apiv1beta1 "sigs.k8s.io/agent-sandbox/extensions/api/v1beta1"
)

// LifecycleApplyConfiguration represents a declarative configuration of the Lifecycle type for use
// with apply.
//
// Lifecycle defines the lifecycle management for the SandboxClaim.
type LifecycleApplyConfiguration struct {
	// shutdownTime is the absolute time when the SandboxClaim expires.
	// This time governs the lifecycle of the claim. It is not propagated to the
	// underlying Sandbox. Instead, the SandboxClaim controller enforces this
	// expiration by deleting the Sandbox resources when the time is reached.
	// If this field is omitted or set to nil, the SandboxClaim itself won't expire.
	// This implies unsetting a Sandbox's ShutdownTime via SandboxClaim isn't supported.
	ShutdownTime *v1.Time `json:"shutdownTime,omitempty"`
	// ttlSecondsAfterFinished limits how long a finished claim is retained.
	// The timer starts from the mirrored Finished condition's LastTransitionTime.
	TTLSecondsAfterFinished *int32 `json:"ttlSecondsAfterFinished,omitempty"`
	// shutdownPolicy determines the behavior when the SandboxClaim expires.
	ShutdownPolicy *apiv1beta1.ShutdownPolicy `json:"shutdownPolicy,omitempty"`
}

// LifecycleApplyConfiguration constructs a declarative configuration of the Lifecycle type for use with
// apply.
func Lifecycle() *LifecycleApplyConfiguration {
	return &LifecycleApplyConfiguration{}
}

// WithShutdownTime sets the ShutdownTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShutdownTime field is set to the value of the last call.
func (b *LifecycleApplyConfiguration) WithShutdownTime(value v1.Time) *LifecycleApplyConfiguration {
	b.ShutdownTime = &value
	return b
}

// WithTTLSecondsAfterFinished sets the TTLSecondsAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterFinished field is set to the value of the last call.
func (b *LifecycleApplyConfiguration) WithTTLSecondsAfterFinished(value int32) *LifecycleApplyConfiguration {
	b.TTLSecondsAfterFinished = &value
	return b
}

// WithShutdownPolicy sets the ShutdownPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShutdownPolicy field is set to the value of the last call.
func (b *LifecycleApplyConfiguration) WithShutdownPolicy(value apiv1beta1.ShutdownPolicy) *LifecycleApplyConfiguration {
	b.ShutdownPolicy = &value
	return b
}
