// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	apiv1beta1 "sigs.k8s.io/agent-sandbox/clients/k8s/applyconfiguration/api/v1beta1"
	extensionsapiv1beta1 "sigs.k8s.io/agent-sandbox/extensions/api/v1beta1"
)

// SandboxTemplateSpecApplyConfiguration represents a declarative configuration of the SandboxTemplateSpec type for use
// with apply.
//
// SandboxTemplateSpec defines the desired state of Sandbox.
type SandboxTemplateSpecApplyConfiguration struct {
	// SandboxBlueprint defines the workload configuration shared with SandboxSpec.
	// NOTE: Once a field is added here, it is promoted to both Sandbox and SandboxTemplate.
	// Since moving fields out is breaking, if unsure whether a new field should be shared,
	// define it in SandboxTemplateSpec (or SandboxSpec) first and promote it here later.
	apiv1beta1.SandboxBlueprintApplyConfiguration `json:",inline"`
	// networkPolicy defines the network policy to be applied to the sandboxes
	// created from this template. A single shared NetworkPolicy is created per Template.
	// Behavior is dictated by the NetworkPolicyManagement field:
	// - If Management is "Unmanaged": This field is completely ignored.
	// - If Management is "Managed" (default) and this field is omitted (nil): The controller
	// automatically applies a strict Secure Default policy:
	// * Ingress: Allow traffic only from the Sandbox Router.
	// * Egress: Allow Public Internet only. Blocks internal IPs (RFC1918), Metadata Server, etc.
	// - If Management is "Managed" and this field is provided: The controller applies your custom rules.
	// Update Behavior:
	// Because the NetworkPolicy is shared at the template level, any updates to these rules
	// will be applied to the single shared policy object. The underlying Kubernetes CNI will then
	// dynamically enforce the updated rules across all existing and future sandboxes
	// referencing this template.
	// NOTE: This is a restricted subset of the standard Kubernetes NetworkPolicySpec.
	// Fields like 'PodSelector' and 'PolicyTypes' are intentionally excluded because
	// they are managed by the controller to ensure strict isolation and default-deny posture.
	// WARNING: This policy enforces a strict "Default Deny" ingress posture.
	// If your Pod uses sidecars (e.g., Istio proxy, monitoring agents) that listen
	// on their own ports, the NetworkPolicy will BLOCK traffic to them by default.
	// You MUST explicitly allow traffic to these sidecar ports using 'Ingress',
	// otherwise the sidecars may fail health checks.
	NetworkPolicy *NetworkPolicySpecApplyConfiguration `json:"networkPolicy,omitempty"`
	// networkPolicyManagement defines whether the controller manages the NetworkPolicy.
	// Valid values are "Managed" (default) or "Unmanaged".
	NetworkPolicyManagement *extensionsapiv1beta1.NetworkPolicyManagement `json:"networkPolicyManagement,omitempty"`
	// envVarsInjectionPolicy allows a SandboxClaim to inject or override environment variables defined in the template.
	// If set to Disallowed, the SandboxClaim will be rejected if it specifies any environment variables.
	EnvVarsInjectionPolicy *extensionsapiv1beta1.EnvVarsInjectionPolicy `json:"envVarsInjectionPolicy,omitempty"`
	// volumeClaimTemplatesPolicy allows a SandboxClaim to inject or override volume claim templates defined in the template.
	// If set to Disallowed, the SandboxClaim will be rejected if it specifies any volume claim templates.
	VolumeClaimTemplatesPolicy *extensionsapiv1beta1.VolumeClaimTemplatesPolicy `json:"volumeClaimTemplatesPolicy,omitempty"`
}

// SandboxTemplateSpecApplyConfiguration constructs a declarative configuration of the SandboxTemplateSpec type for use with
// apply.
func SandboxTemplateSpec() *SandboxTemplateSpecApplyConfiguration {
	return &SandboxTemplateSpecApplyConfiguration{}
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *SandboxTemplateSpecApplyConfiguration) WithPodTemplate(value *apiv1beta1.PodTemplateApplyConfiguration) *SandboxTemplateSpecApplyConfiguration {
	b.SandboxBlueprintApplyConfiguration.PodTemplate = value
	return b
}

// WithVolumeClaimTemplates adds the given value to the VolumeClaimTemplates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeClaimTemplates field.
func (b *SandboxTemplateSpecApplyConfiguration) WithVolumeClaimTemplates(values ...*apiv1beta1.PersistentVolumeClaimTemplateApplyConfiguration) *SandboxTemplateSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumeClaimTemplates")
		}
		b.SandboxBlueprintApplyConfiguration.VolumeClaimTemplates = append(b.SandboxBlueprintApplyConfiguration.VolumeClaimTemplates, *values[i])
	}
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *SandboxTemplateSpecApplyConfiguration) WithService(value bool) *SandboxTemplateSpecApplyConfiguration {
	b.SandboxBlueprintApplyConfiguration.Service = &value
	return b
}

// WithNetworkPolicy sets the NetworkPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkPolicy field is set to the value of the last call.
func (b *SandboxTemplateSpecApplyConfiguration) WithNetworkPolicy(value *NetworkPolicySpecApplyConfiguration) *SandboxTemplateSpecApplyConfiguration {
	b.NetworkPolicy = value
	return b
}

// WithNetworkPolicyManagement sets the NetworkPolicyManagement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkPolicyManagement field is set to the value of the last call.
func (b *SandboxTemplateSpecApplyConfiguration) WithNetworkPolicyManagement(value extensionsapiv1beta1.NetworkPolicyManagement) *SandboxTemplateSpecApplyConfiguration {
	b.NetworkPolicyManagement = &value
	return b
}

// WithEnvVarsInjectionPolicy sets the EnvVarsInjectionPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnvVarsInjectionPolicy field is set to the value of the last call.
func (b *SandboxTemplateSpecApplyConfiguration) WithEnvVarsInjectionPolicy(value extensionsapiv1beta1.EnvVarsInjectionPolicy) *SandboxTemplateSpecApplyConfiguration {
	b.EnvVarsInjectionPolicy = &value
	return b
}

// WithVolumeClaimTemplatesPolicy sets the VolumeClaimTemplatesPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeClaimTemplatesPolicy field is set to the value of the last call.
func (b *SandboxTemplateSpecApplyConfiguration) WithVolumeClaimTemplatesPolicy(value extensionsapiv1beta1.VolumeClaimTemplatesPolicy) *SandboxTemplateSpecApplyConfiguration {
	b.VolumeClaimTemplatesPolicy = &value
	return b
}
