// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// SandboxWarmPoolSpecApplyConfiguration represents a declarative configuration of the SandboxWarmPoolSpec type for use
// with apply.
//
// SandboxWarmPoolSpec defines the desired state of SandboxWarmPool.
type SandboxWarmPoolSpecApplyConfiguration struct {
	// replicas is the desired number of sandboxes in the pool.
	// This field is controlled by an HPA if specified.
	Replicas *int32 `json:"replicas,omitempty"`
	// sandboxTemplateRef - name of the SandboxTemplate to be used for creating a Sandbox
	// Warning: Any change to the json tag "sandboxTemplateRef" must be synchronized with the TemplateRefField constant.
	TemplateRef *SandboxTemplateRefApplyConfiguration `json:"sandboxTemplateRef,omitempty"`
	// updateStrategy - strategy for updating the SandboxWarmPool pods based on sandboxTemplateRef name change or underlying template changes
	UpdateStrategy *SandboxWarmPoolUpdateStrategyApplyConfiguration `json:"updateStrategy,omitempty"`
}

// SandboxWarmPoolSpecApplyConfiguration constructs a declarative configuration of the SandboxWarmPoolSpec type for use with
// apply.
func SandboxWarmPoolSpec() *SandboxWarmPoolSpecApplyConfiguration {
	return &SandboxWarmPoolSpecApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *SandboxWarmPoolSpecApplyConfiguration) WithReplicas(value int32) *SandboxWarmPoolSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *SandboxWarmPoolSpecApplyConfiguration) WithTemplateRef(value *SandboxTemplateRefApplyConfiguration) *SandboxWarmPoolSpecApplyConfiguration {
	b.TemplateRef = value
	return b
}

// WithUpdateStrategy sets the UpdateStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateStrategy field is set to the value of the last call.
func (b *SandboxWarmPoolSpecApplyConfiguration) WithUpdateStrategy(value *SandboxWarmPoolUpdateStrategyApplyConfiguration) *SandboxWarmPoolSpecApplyConfiguration {
	b.UpdateStrategy = value
	return b
}
