// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	agentsandboxapiv1beta1 "sigs.k8s.io/agent-sandbox/api/v1beta1"
	apiv1beta1 "sigs.k8s.io/agent-sandbox/extensions/api/v1beta1"
)

// SandboxClaimSpecApplyConfiguration represents a declarative configuration of the SandboxClaimSpec type for use
// with apply.
//
// SandboxClaimSpec defines the desired state of Sandbox.
type SandboxClaimSpecApplyConfiguration struct {
	// sandboxTemplateRef defines the name of the SandboxTemplate to be used for creating a Sandbox.
	TemplateRef *SandboxTemplateRefApplyConfiguration `json:"sandboxTemplateRef,omitempty"`
	// lifecycle defines when and how the SandboxClaim should be shut down.
	Lifecycle *LifecycleApplyConfiguration `json:"lifecycle,omitempty"`
	// warmpool specifies the warm pool policy for sandbox adoption.
	// - "none": Do not use any warm pool, always create fresh sandboxes
	// - "default": Use default behavior, select from all matching warm pools (default)
	// - A warm pool name: Select only from the specified warm pool (e.g., "fast-pool", "secure-pool")
	WarmPool *apiv1beta1.WarmPoolPolicy `json:"warmpool,omitempty"`
	// additionalPodMetadata defines the labels and annotations to be propagated to the Sandbox Pod.
	// Label values are limited to 63 characters and must match Kubernetes label value patterns.
	AdditionalPodMetadata *agentsandboxapiv1beta1.PodMetadata `json:"additionalPodMetadata,omitempty"`
	// env is a list of environment variables to inject into the sandbox
	Env []EnvVarApplyConfiguration `json:"env,omitempty"`
}

// SandboxClaimSpecApplyConfiguration constructs a declarative configuration of the SandboxClaimSpec type for use with
// apply.
func SandboxClaimSpec() *SandboxClaimSpecApplyConfiguration {
	return &SandboxClaimSpecApplyConfiguration{}
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *SandboxClaimSpecApplyConfiguration) WithTemplateRef(value *SandboxTemplateRefApplyConfiguration) *SandboxClaimSpecApplyConfiguration {
	b.TemplateRef = value
	return b
}

// WithLifecycle sets the Lifecycle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lifecycle field is set to the value of the last call.
func (b *SandboxClaimSpecApplyConfiguration) WithLifecycle(value *LifecycleApplyConfiguration) *SandboxClaimSpecApplyConfiguration {
	b.Lifecycle = value
	return b
}

// WithWarmPool sets the WarmPool field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WarmPool field is set to the value of the last call.
func (b *SandboxClaimSpecApplyConfiguration) WithWarmPool(value apiv1beta1.WarmPoolPolicy) *SandboxClaimSpecApplyConfiguration {
	b.WarmPool = &value
	return b
}

// WithAdditionalPodMetadata sets the AdditionalPodMetadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdditionalPodMetadata field is set to the value of the last call.
func (b *SandboxClaimSpecApplyConfiguration) WithAdditionalPodMetadata(value agentsandboxapiv1beta1.PodMetadata) *SandboxClaimSpecApplyConfiguration {
	b.AdditionalPodMetadata = &value
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *SandboxClaimSpecApplyConfiguration) WithEnv(values ...*EnvVarApplyConfiguration) *SandboxClaimSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnv")
		}
		b.Env = append(b.Env, *values[i])
	}
	return b
}
