// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// SandboxStatusApplyConfiguration represents a declarative configuration of the SandboxStatus type for use
// with apply.
type SandboxStatusApplyConfiguration struct {
	// name is the name of the Sandbox created from this claim
	Name *string `json:"name,omitempty"`
	// podIPs are the IP addresses of the underlying pod.
	// A pod may have multiple IPs in dual-stack clusters.
	PodIPs []string `json:"podIPs,omitempty"`
}

// SandboxStatusApplyConfiguration constructs a declarative configuration of the SandboxStatus type for use with
// apply.
func SandboxStatus() *SandboxStatusApplyConfiguration {
	return &SandboxStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SandboxStatusApplyConfiguration) WithName(value string) *SandboxStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithPodIPs adds the given value to the PodIPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PodIPs field.
func (b *SandboxStatusApplyConfiguration) WithPodIPs(values ...string) *SandboxStatusApplyConfiguration {
	for i := range values {
		b.PodIPs = append(b.PodIPs, values[i])
	}
	return b
}
