// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	apiv1beta1 "sigs.k8s.io/agent-sandbox/api/v1beta1"
	applyconfigurationapiv1beta1 "sigs.k8s.io/agent-sandbox/clients/k8s/applyconfiguration/api/v1beta1"
)

// SandboxClaimSpecApplyConfiguration represents a declarative configuration of the SandboxClaimSpec type for use
// with apply.
//
// SandboxClaimSpec defines the desired state of Sandbox.
type SandboxClaimSpecApplyConfiguration struct {
	// warmPoolRef targets the specific pre-warmed infrastructure pool to check out from.
	WarmPoolRef *SandboxWarmPoolRefApplyConfiguration `json:"warmPoolRef,omitempty"`
	// lifecycle defines when and how the SandboxClaim should be shut down.
	Lifecycle *LifecycleApplyConfiguration `json:"lifecycle,omitempty"`
	// additionalPodMetadata defines the labels and annotations to be propagated to the Sandbox Pod.
	// Label values are limited to 63 characters and must match Kubernetes label value patterns.
	AdditionalPodMetadata *apiv1beta1.PodMetadata `json:"additionalPodMetadata,omitempty"`
	// env is a list of environment variables to inject into the sandbox.
	// Please note adding this field means the Sandbox will always be cold-started from the
	// template of the warmpool.
	Env []EnvVarApplyConfiguration `json:"env,omitempty"`
	// volumeClaimTemplates is a list of persistent volume claims to be created for the sandbox.
	// Specifying this field forces a cold start because warm pool pods will not have these volumes.
	VolumeClaimTemplates []applyconfigurationapiv1beta1.PersistentVolumeClaimTemplateApplyConfiguration `json:"volumeClaimTemplates,omitempty"`
}

// SandboxClaimSpecApplyConfiguration constructs a declarative configuration of the SandboxClaimSpec type for use with
// apply.
func SandboxClaimSpec() *SandboxClaimSpecApplyConfiguration {
	return &SandboxClaimSpecApplyConfiguration{}
}

// WithWarmPoolRef sets the WarmPoolRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WarmPoolRef field is set to the value of the last call.
func (b *SandboxClaimSpecApplyConfiguration) WithWarmPoolRef(value *SandboxWarmPoolRefApplyConfiguration) *SandboxClaimSpecApplyConfiguration {
	b.WarmPoolRef = value
	return b
}

// WithLifecycle sets the Lifecycle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lifecycle field is set to the value of the last call.
func (b *SandboxClaimSpecApplyConfiguration) WithLifecycle(value *LifecycleApplyConfiguration) *SandboxClaimSpecApplyConfiguration {
	b.Lifecycle = value
	return b
}

// WithAdditionalPodMetadata sets the AdditionalPodMetadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdditionalPodMetadata field is set to the value of the last call.
func (b *SandboxClaimSpecApplyConfiguration) WithAdditionalPodMetadata(value apiv1beta1.PodMetadata) *SandboxClaimSpecApplyConfiguration {
	b.AdditionalPodMetadata = &value
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *SandboxClaimSpecApplyConfiguration) WithEnv(values ...*EnvVarApplyConfiguration) *SandboxClaimSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnv")
		}
		b.Env = append(b.Env, *values[i])
	}
	return b
}

// WithVolumeClaimTemplates adds the given value to the VolumeClaimTemplates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeClaimTemplates field.
func (b *SandboxClaimSpecApplyConfiguration) WithVolumeClaimTemplates(values ...*applyconfigurationapiv1beta1.PersistentVolumeClaimTemplateApplyConfiguration) *SandboxClaimSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumeClaimTemplates")
		}
		b.VolumeClaimTemplates = append(b.VolumeClaimTemplates, *values[i])
	}
	return b
}
