// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// WorkspaceResourceOverrideApplyConfiguration represents a declarative configuration of the WorkspaceResourceOverride type for use
// with apply.
//
// WorkspaceResourceOverride defines per-claim resource requirement overrides
// for a named PodSpec container or init container. Requests and limits are
// merged by resource name; non-empty claims replace the target container's
// resource claims.
type WorkspaceResourceOverrideApplyConfiguration struct {
	// containerName specifies the target regular container or init container for
	// the resource override.
	ContainerName *string `json:"containerName,omitempty"`
	// resources specifies resource requirements to merge into the target container.
	// Request and limit entries left unset keep the values from the SandboxTemplate.
	// Non-empty claims replace the target container's resource claims.
	Resources *v1.ResourceRequirements `json:"resources,omitempty"`
}

// WorkspaceResourceOverrideApplyConfiguration constructs a declarative configuration of the WorkspaceResourceOverride type for use with
// apply.
func WorkspaceResourceOverride() *WorkspaceResourceOverrideApplyConfiguration {
	return &WorkspaceResourceOverrideApplyConfiguration{}
}

// WithContainerName sets the ContainerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerName field is set to the value of the last call.
func (b *WorkspaceResourceOverrideApplyConfiguration) WithContainerName(value string) *WorkspaceResourceOverrideApplyConfiguration {
	b.ContainerName = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *WorkspaceResourceOverrideApplyConfiguration) WithResources(value v1.ResourceRequirements) *WorkspaceResourceOverrideApplyConfiguration {
	b.Resources = &value
	return b
}
