// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SandboxStatusApplyConfiguration represents a declarative configuration of the SandboxStatus type for use
// with apply.
//
// SandboxStatus defines the observed state of Sandbox.
type SandboxStatusApplyConfiguration struct {
	// serviceFQDN that is valid for default cluster settings
	// The domain defaults to cluster.local but is configurable via the controller's --cluster-domain flag.
	ServiceFQDN *string `json:"serviceFQDN,omitempty"`
	// service is a sandbox-example
	Service *string `json:"service,omitempty"`
	// conditions defines the status conditions array
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// selector is the label selector for pods.
	LabelSelector *string `json:"selector,omitempty"`
	// podIPs are the IP addresses of the underlying pod.
	// A pod may have multiple IPs in dual-stack clusters.
	PodIPs []string `json:"podIPs,omitempty"`
	// nodeName is the name of the node where the underlying pod is scheduled.
	NodeName *string `json:"nodeName,omitempty"`
}

// SandboxStatusApplyConfiguration constructs a declarative configuration of the SandboxStatus type for use with
// apply.
func SandboxStatus() *SandboxStatusApplyConfiguration {
	return &SandboxStatusApplyConfiguration{}
}

// WithServiceFQDN sets the ServiceFQDN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceFQDN field is set to the value of the last call.
func (b *SandboxStatusApplyConfiguration) WithServiceFQDN(value string) *SandboxStatusApplyConfiguration {
	b.ServiceFQDN = &value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *SandboxStatusApplyConfiguration) WithService(value string) *SandboxStatusApplyConfiguration {
	b.Service = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SandboxStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SandboxStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *SandboxStatusApplyConfiguration) WithLabelSelector(value string) *SandboxStatusApplyConfiguration {
	b.LabelSelector = &value
	return b
}

// WithPodIPs adds the given value to the PodIPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PodIPs field.
func (b *SandboxStatusApplyConfiguration) WithPodIPs(values ...string) *SandboxStatusApplyConfiguration {
	for i := range values {
		b.PodIPs = append(b.PodIPs, values[i])
	}
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *SandboxStatusApplyConfiguration) WithNodeName(value string) *SandboxStatusApplyConfiguration {
	b.NodeName = &value
	return b
}
