// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// SandboxBlueprintApplyConfiguration represents a declarative configuration of the SandboxBlueprint type for use
// with apply.
//
// SandboxBlueprint defines the configuration shared between Sandbox and SandboxTemplate.
// It deliberately excludes runtime-only fields (operatingMode, lifecycle).
type SandboxBlueprintApplyConfiguration struct {
	// podTemplate describes the pod that will be created in the sandbox.
	// Note: When provisioned via a SandboxTemplate (such as by a SandboxClaim or SandboxWarmPool),
	// if AutomountServiceAccountToken is not specified in the PodSpec, the controller defaults it
	// to false to ensure a secure-by-default environment.
	PodTemplate *PodTemplateApplyConfiguration `json:"podTemplate,omitempty"`
	// volumeClaimTemplates is a list of claims that the sandbox pod is allowed to reference.
	// When creating a sandbox, PVCs will be created from these templates.
	// Every claim in this list must have at least one matching access mode with a provisioner volume.
	// NOTE: This list is atomic. Updates to this field will replace the entire list rather than merging with existing entries.
	VolumeClaimTemplates []PersistentVolumeClaimTemplateApplyConfiguration `json:"volumeClaimTemplates,omitempty"`
	// service controls whether the controller should automatically create a
	// headless Service for the Sandbox workload.
	// When unset, the controller preserves existing Services for backward
	// compatibility but does not create new ones. Set to true to enable or false
	// to explicitly disable and remove the Service.
	Service *bool `json:"service,omitempty"`
}

// SandboxBlueprintApplyConfiguration constructs a declarative configuration of the SandboxBlueprint type for use with
// apply.
func SandboxBlueprint() *SandboxBlueprintApplyConfiguration {
	return &SandboxBlueprintApplyConfiguration{}
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *SandboxBlueprintApplyConfiguration) WithPodTemplate(value *PodTemplateApplyConfiguration) *SandboxBlueprintApplyConfiguration {
	b.PodTemplate = value
	return b
}

// WithVolumeClaimTemplates adds the given value to the VolumeClaimTemplates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeClaimTemplates field.
func (b *SandboxBlueprintApplyConfiguration) WithVolumeClaimTemplates(values ...*PersistentVolumeClaimTemplateApplyConfiguration) *SandboxBlueprintApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumeClaimTemplates")
		}
		b.VolumeClaimTemplates = append(b.VolumeClaimTemplates, *values[i])
	}
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *SandboxBlueprintApplyConfiguration) WithService(value bool) *SandboxBlueprintApplyConfiguration {
	b.Service = &value
	return b
}
